### ISSUE TITLE
-mgprel doesn't use gp-relative offsets for subfield accesses

### ISSUE THREAD

**Issue by pizzarollsroyce** [SupernaviX/v810-llvm#11]
Values loaded or stored relative to a global via a nested struct (or chain of such) should have an address that is statically knowable at compile time as an offset from `gp`, but these accesses are pulled out into a separate register before being resolved.

Input:

```c
#include <stdint.h>

struct C {
  uint32_t val;
};
struct B {
  uint32_t val;
  struct C c;
};
struct A {
  uint32_t val;
  struct B b;
};

struct A a;

extern int GetVal() {
  return a.b.c.val;
}
```

Result:

```as
<GetVal>:
  movea -0x8000, r4, r6
  ld.w 0x8[r6], r10
  jmp [r31]
```

Ideally, it would collapse the first two instructions to produce:
```as
<GetVal>:
  ld.w -0x7FF8[r4], r10
  jmp [r31]
```

**Comment by SupernaviX** [comment]
It looks like this is happening because we [disable "offset folding" explicitly](https://github.com/SupernaviX/v810-llvm/blob/55c928bbd5bbebd00a4f7b7f4c282893ea6d17a7/llvm/lib/Target/V810/V810ISelLowering.cpp#L811-L815). And I disabled it because in several scenarios, clang generates worse code with it on. Specifically, it generates code with lots of constants instead of using offsets from the same memory address.

Input:
```c
typedef struct mode_t {
	void (*show)(void);
	void (*hide)(void);
	void (*update)(void);
} mode_t;

static void nothing(void) {}

static mode_t next_mode = {
	.show = nothing,
	.hide = nothing,
	.update = nothing,
};

void mode_set(mode_t next) {
	next_mode = next;
}
```

Result without offset folding:
```asm
	movhi hi(next_mode), r0, r9
	movea lo(next_mode), r9, r9
	st.w r6, 0[r9]
	st.w r7, 4[r9]
	st.w r8, 8[r9]
	jmp [r31]
```

Result with offset folding:
```asm
	movhi hi(next_mode), r0, r9
	movea lo(next_mode), r9, r9
	st.w r6, 0[r9]
	movhi hi(next_mode+4), r0, r6
	movea lo(next_mode+4), r6, r6
	st.w r7, 0[r6]
	movhi hi(next_mode+8), r0, r6
	movea lo(next_mode+8), r6, r6
	st.w r8, 0[r6]
	jmp [r31]
```

Clearly, offset folding _should_ be on (since it is legal after all), but also we need to fix that bad code to keep it on.
